sudo: false

language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer
    - build/cache

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/atoum -ncc -d atoum/

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
